name: Build and Publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm32v6
          push: true
          tags: zocaloict/certbot_duckdns:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
